name: "backup"
version: "0.1.1"
usage: "backup/restore releases in a namespace to/from a file"
description: "backup/restore releases in a namespace to/from a file"
command: "$HELM_PLUGIN_DIR/bin/backup"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
